### ISSUE TITLE
named_args not working properly

### ISSUE THREAD

**Issue by mamarillo** [JustinAiken/active_scheduler#12]
my job class looks something like this:

```
class MyJob < ApplicationJob
 def perform(arg0 = false, arg1 = 1)
  puts "arg0=#{arg0} ~~~ arg1=#{arg1}"
 end
end
```

resque_schedule.yml looks like this:
```
MyJob:
  cron: "* * * * *"
  queue: "default"
  named_args: true
  args:
    - arg0: false
      arg1: 0
```

but the result is 
`arg0={arg0: false, arg1: 0} ~~~ arg1=1`
